export const actionTypes = {
    SET_INITIAL_STATE: 'SET_INITIAL_STATE',
    ADD_LIST: 'ADD_LIST',
    DELETE_LIST: 'DELETE_LIST',
    ADD_TODO: 'ADD_TODO',
    DELETE_TODO: 'DELETE_TODO',
    EDIT_TODO: 'EDIT_TODO',
    COMPLETED_TODO: 'COMPLETED_TODO',
    SET_ITEM_TODO: 'SET_ITEM_TODO',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR'
}