export const actionTypes = {
    ADD_LIST: 'ADD_LIST',
    DELETE_LIST: 'DELETE_LIST',
    ADD_TODO: 'ADD_TODO',
    DELETE_TODO: 'DELETE_TODO',
    EDIT_TODO: 'EDIT_TODO',
    COMPLETED_TODO: 'COMPLETED_TODO'
}